// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeS0AIaD8qxBR7NTe1W4tDbVxSOdkKP-Q',
    appId: '1:80611561466:web:f23f4be9c2457c09e35e43',
    messagingSenderId: '80611561466',
    projectId: 'evently-fd06f',
    authDomain: 'evently-fd06f.firebaseapp.com',
    storageBucket: 'evently-fd06f.firebasestorage.app',
    measurementId: 'G-CR8C9ZD11P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB93oXUCu2hjQErs4aFCEXVxWX5QsKhP9E',
    appId: '1:80611561466:android:e0be08f24711e44ee35e43',
    messagingSenderId: '80611561466',
    projectId: 'evently-fd06f',
    storageBucket: 'evently-fd06f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVP8ZLL-WBBX14_NnXEemqxW8p2pkYe0',
    appId: '1:80611561466:ios:cb6b0c21f11f74bde35e43',
    messagingSenderId: '80611561466',
    projectId: 'evently-fd06f',
    storageBucket: 'evently-fd06f.firebasestorage.app',
    androidClientId: '80611561466-e1bt79ktojlenms5mgrd7c3gbugtf3e0.apps.googleusercontent.com',
    iosClientId: '80611561466-202pvmd67r4qkguh2hpsmjgq8j54lsa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyApp',
  );
}
